UPR:
  data_file: 'gs://classification_data/UPR.csv'
  pkl_file: 'gs://classification_data/UPR.pkl'
  label_col: 'Issue'
  text_col: 'Recommendation'
  delimiter: ','
  sep: ','

PlanInternational:
  data_file: 'gs://classification_data/PlanInternational_multilabel.csv'
  pkl_file: 'gs://classification_data/PLAN.pkl'
  label_col: 'topics'
  text_col: 'Paragraph text'
  delimiter: ','
  sep: ','
