UPR:
  data_file: 'gs://classification_data/UPR.csv'
  pkl_file: 'gs://classification_data/UPR.pkl'
  label_col: 'Issue'
  text_col: 'Recommendation'
  delimiter: ','
  sep: ','

PlanInternational:
  data_file: 'gs://classification_data/PlanInternational_multilabel.csv'
  pkl_file: 'gs://classification_data/PLAN.pkl'
  label_col: 'topics'
  text_col: 'Paragraph text'
  delimiter: ','
  sep: ','

PlanInternational_paragraphs:
  data_file: 'gs://classification_data/PlanInternational_paragraphs.csv'
  pkl_file: 'gs://classification_data/PLAN_paragraphs.pkl'
  label_col: 'label'
  text_col: 'text'
  delimiter: ','
  sep: ','

UHRI_themes:
  data_file: 'gs://classification_data/UHRI.csv'
  pkl_file: 'gs://classification_data/UHRI_themes.pkl'
  label_col: 'themes'
  text_col: 'text'
  delimiter: ','
  sep: '$'

UHRI_affected_persons:
  data_file: 'gs://classification_data/UHRI.csv'
  pkl_file: 'gs://classification_data/UHRI_affected_persons.pkl'
  label_col: 'affected_persons'
  text_col: 'text'
  delimiter: ','
  sep: '$'

UHRI_sdgs:
  data_file: 'gs://classification_data/UHRI.csv'
  pkl_file: 'gs://classification_data/UHRI_sdgs.pkl'
  label_col: 'sdgs'
  text_col: 'text'
  delimiter: ','
  sep: '$'
